module.exports = {
    askAcisi: [
        // Arabesk Klasikleri
        "İbrahim Tatlıses Mavi Mavi",
        "Müslüm Gürses Nilüfer",
        "Orhan Gencebay Dil Yarası",
        "Ferdi Tayfur Emmoğlu",
        "İbrahim Tatlıses Haydi Bastır",
        "Müslüm Gürses Affet",
        "Orhan Gencebay Hatasız Kul Olmaz",
        "Ferdi Tayfur Sen De Mi Leyla",
        "İbrahim Tatlıses Semmame",        "Müslüm Gürses Esmer Güzel",
        "Coşkun Sabah Kara Sevda",
        "Ahmet Özhan Bir Ömür",
        "Zeki Müren Şimdi Uzaklardasın",
        "İbrahim Tatlıses Leylim Ley",
        "Müslüm Gürses İtirazım Var",
        "Orhan Gencebay Batsın Bu Dünya",
        "Ferdi Tayfur Huzurum Kalmadı",
        "İbrahim Tatlıses Kara Zindan",
        "Müslüm Gürses Hangimiz Sevmedik",        "Orhan Gencebay Gönül Sabreyle",
        "Ferdi Tayfur Günahkarım",
        "İbrahim Tatlıses Seni Sevmeyen Ölsün",
        "Müslüm Gürses Adını Sen Koy",
        "Orhan Gencebay Aşkın Nur Yüzü",
        "Ferdi Tayfur Bu Kalp Seni Unutur Mu",
        "İbrahim Tatlıses Tek Tek",
        "Müslüm Gürses Yaşayamadık",        "Orhan Gencebay Sevda Yanığı",
        "Ferdi Tayfur Kara Sevda",
        "İbrahim Tatlıses Korkarım",        "Müslüm Gürses Emmioğlu",
        "Ferdi Tayfur Allah Affetsin",
        "İbrahim Tatlıses Bebek",
        "Müslüm Gürses Beddua",
        "Orhan Gencebay Feryad",
        "Ferdi Tayfur Vazgeçtim",
        "İbrahim Tatlıses Nankör Sevgili",
        
        // Müslüm Gürses Özel
        "Müslüm Gürses Hayallerim Suya Düştü",
        "Müslüm Gürses İntizar",
        "Müslüm Gürses Suya Düşen Ağlar",
        "Müslüm Gürses Beddua",
        "Müslüm Gürses Yaşayamadık",
        "Müslüm Gürses Altın Yüzüğüm",
        "Müslüm Gürses Olmadı Karagözlüm",
        "Müslüm Gürses Sevda Çiçeği",
        "Müslüm Gürses Istemem",
        "Müslüm Gürses Affet",
        "Müslüm Gürses Mecnunum",
        "Müslüm Gürses İtişme",
        "Müslüm Gürses Beklenen Şarkı",        "Müslüm Gürses Günaydın",
        "Müslüm Gürses Sızım",
        "Müslüm Gürses Açılmadın Goncam",
        "Müslüm Gürses Ay Işığında",
        
        // İbrahim Tatlıses Özel
        "İbrahim Tatlıses Yara Bende",
        "İbrahim Tatlıses Eyvallah",
        "İbrahim Tatlıses Mutlu Ol Yeter",
        "İbrahim Tatlıses Beni Vur",
        "İbrahim Tatlıses Sarıl Bana",
        "İbrahim Tatlıses Seher Vakti",
        "İbrahim Tatlıses Neden",
        "İbrahim Tatlıses Gül Yüzlüm",        "İbrahim Tatlıses Gözlerim",
        "İbrahim Tatlıses Söz Olur",
        "İbrahim Tatlıses Buzlar Çözülmüyor",        "İbrahim Tatlıses Kara Kara",
        "İbrahim Tatlıses Benim de Kalbim Var",
        "İbrahim Tatlıses Haram Olsun",
        
        // Orhan Gencebay Özel
        "Orhan Gencebay Olmadı Yar",
        "Orhan Gencebay Bir Teselli Ver",
        "Orhan Gencebay Ne Varmış Aşkta",        "Orhan Gencebay Bir Zamanlar",
        "Orhan Gencebay Beyaz Kelebekler",
        "Orhan Gencebay Seni Düşünmek",
        "Orhan Gencebay Kalbin Yoldaş Olsun",        "Orhan Gencebay Dil Yarası",
        "Orhan Gencebay Gerçek Aşk",
        "Orhan Gencebay Gülüm",        "Orhan Gencebay Gel Barışalım",
        "Orhan Gencebay Misket",
        "Orhan Gencebay Kahpedir",
        "Orhan Gencebay Darısı Başımıza",
        "Orhan Gencebay Ne Derdin Varsa Söyle",
        "Orhan Gencebay Eylül Akşamı",
        
        // Ferdi Tayfur Özel
        "Ferdi Tayfur Bu Gece Sonuncu Gece",
        "Ferdi Tayfur İhanetten Geri Kalan",
        "Ferdi Tayfur Sarhoşum Bu Gece",        "Ferdi Tayfur Bitmeyen Ağrı",
        "Ferdi Tayfur Mahşer-i Aşk",
        "Ferdi Tayfur Ağlayan Gözlüm",
        "Ferdi Tayfur Adak",
        "Ferdi Tayfur Ayrılmam",
        "Ferdi Tayfur Bundan Böyle",        "Ferdi Tayfur Bu Şarkının Sözleri",
        "Ferdi Tayfur Canın Sağ Olsun",        "Ferdi Tayfur Cemile",
        "Ferdi Tayfur En Sevdiğim Şarkı",        "Ferdi Tayfur Giden İnsanlar",
        "Ferdi Tayfur Hiç Öyle Bir Sevdanız Oldu Mu",
        
        // 1000 Damardan Aşk Acısı Eklentiler
        "Murat Göğebakan Vurgunum",
        "Halil Sezai İsyan",
        "Cem Adrian Ben Seni Çok Sevdim",
        "Feridun Düzağaç Alev Alev",
        "Duman Belki Alışman Lazım",
        "Şebnem Ferah Sil Baştan",
        "Teoman Renkli Rüyalar Oteli",
        "Sezen Aksu Tükeneceğiz",
        "Candan Erçetin Yeter Ki",
        "Zakkum Ben Ne Yangınlar Gördüm",
        "Fikret Kızılok Bu Kalp Seni Unutur mu",
        "Göksel Acıyor",
        "Levent Yüksel Kadınım",
        "Tarkan Unutmamalı",
        "Yıldız Tilbe El Adamı",
        "Ahmet Kaya Kum Gibi",
        "Cem Karaca Bu Son Olsun",
        "Ajda Pekkan O Benim Dünyam",
        
        // Ek Müslüm Gürses Şarkıları
        "Müslüm Gürses Mumya",
        "Müslüm Gürses Meyhaneci",
        "Müslüm Gürses Çile Bülbülü",
        "Müslüm Gürses Esrarlı Gözler",
        "Müslüm Gürses Hasret Rüzgarları",
        "Müslüm Gürses İçimde Yanar Bir Ateş",
        "Müslüm Gürses Kahroldum",
        "Müslüm Gürses Kısacık Bir Rüyaydı",
        "Müslüm Gürses Sana da Beyim",
        "Müslüm Gürses Sevda Yakar Beni",
        "Müslüm Gürses Son Defa",
        "Müslüm Gürses Susma Kalbim",
        "Müslüm Gürses Şu Yalan Dünya",
        "Müslüm Gürses Yalnız Yaşayıp",
        "Müslüm Gürses Buralarda Bir Kız Vardı",
        
        // Ek İbrahim Tatlıses Şarkıları
        "İbrahim Tatlıses Ağlama Yarim",
        "İbrahim Tatlıses Aklımda Fikrimde Sen Varsın",
        "İbrahim Tatlıses Aramam",
        "İbrahim Tatlıses Çocukluk",
        "İbrahim Tatlıses Dert Nedir",
        "İbrahim Tatlıses Fosforlu Cevriyem",
        "İbrahim Tatlıses Gidiyorum",
        "İbrahim Tatlıses Hayırsız Evlat",
        "İbrahim Tatlıses İmdat",
        "İbrahim Tatlıses Masum",
        "İbrahim Tatlıses Mavi Süvari",
        "İbrahim Tatlıses Olmaz Olsun",
        "İbrahim Tatlıses Sabah Olmuyor",
        "İbrahim Tatlıses Sevmeyecek Gönlüm",
        "İbrahim Tatlıses Şaşkınım",
        "İbrahim Tatlıses Üç Kalp",
        "İbrahim Tatlıses Yaralıyım",
        "İbrahim Tatlıses Yüce Dağ Başında",
        "İbrahim Tatlıses Zoruna Gitti",        "İbrahim Tatlıses Şu Kalbimin Efendisi",
        
        // Ek Orhan Gencebay Şarkıları
        "Orhan Gencebay İnsanoğlu",
        "Orhan Gencebay Garip Dostu",
        "Orhan Gencebay Küçük Yaşta",
        "Orhan Gencebay Pınar Başında",
        "Orhan Gencebay Sevdim",
        "Orhan Gencebay Ümit Hırsızı",
        "Orhan Gencebay Yaşama Sevinci",
        "Orhan Gencebay Zalim Sultan",
        "Orhan Gencebay Rüzgar",
        "Orhan Gencebay Tamirci Çırağı",
        "Orhan Gencebay Sevmek",
        "Orhan Gencebay Şarkım Dinle",
        "Orhan Gencebay Yol",
        "Orhan Gencebay Beyhude",
        "Orhan Gencebay Bir Sevda Masalı",
        "Orhan Gencebay Gönülden Gönüle",
        "Orhan Gencebay İstersen",
        "Orhan Gencebay Kalbim",
        "Orhan Gencebay Sevenler",
        
        // Ek Ferdi Tayfur Şarkıları
        "Ferdi Tayfur Ah Be Gülüm",
        "Ferdi Tayfur Aşkımız Bitecek",
        "Ferdi Tayfur Bak Beni Görsen Tanımazsın",
        "Ferdi Tayfur Çeşm-i Siyahım",
        "Ferdi Tayfur Gel Benim Ol",
        "Ferdi Tayfur Gülmemek Elde mi",
        "Ferdi Tayfur Haram Oldu",
        "Ferdi Tayfur Kalbimi Kırdığın Gün",
        "Ferdi Tayfur Kara Gözlüm",
        "Ferdi Tayfur Meyhaneci",
        "Ferdi Tayfur Neylersin",
        "Ferdi Tayfur Sorma",
        "Ferdi Tayfur Şoför",
        "Ferdi Tayfur Tek Başına",
        "Ferdi Tayfur Veda",
        "Ferdi Tayfur Yalnızlık",
        "Ferdi Tayfur Yar Dedin",
        "Ferdi Tayfur Yine Aynı Rüya",
        "Ferdi Tayfur Yokluğunda",
        "Ferdi Tayfur Zordur",
        
        // Kadın Seslerin Aşk Acısı
        "Kibariye Yaşamak Bu Değil",
        "Kibariye Yalan",
        "Kibariye Sen Affetsen Ben Affetmem",
        "Kibariye Ağlarım Hem de Çok Ağlarım",
        "Kibariye Bugün Aylardan Kasım",
        "Kibariye Kaçın Kurası",
        "Kibariye Kim Bilir",
        "Kibariye Kulakları Çın Çın Ötsün",
        "Kibariye Oy Benim Canım",
        
        // Modern Aşk Acısı Şarkıları  
        "Emre Aydın Hoş Geldin",
        "Emre Aydın Belki Üstümüzden Kuşlar Geçer",
        "Kenan Doğulu Arada Sırada",
        "Hande Yener Sen Yoluna Ben Yoluma",
        "Sibel Can Yalnız Kaldım",
        "Demet Akalın Hayaller",
        "Ebru Gündeş Seni Seviyorum",
        "Sıla Yan Benimle",
        "Candan Erçetin Aldırma Deli Gönül",
        "Bengü İki Medeni İnsan",
          // Yeni Nesil Arabesk - Sadece Aşk Acısı
        "Cengiz Kurtoğlu Seni Seviyorum",
        "Selami Şahin Gelmez Oldun",
        "Özcan Deniz Aşk",
        "Rafet El Roman Unuturum Elbet",
        "Mustafa Ceceli Sultan",
        "Alişan Sevdim Seni",
        "Ümit Besen Nikah Masası",
        "Berdan Mardini Kırgınım",
        "İskender Paydaş Yorgunum",
        "Murat Uyar Sevda Yelleri",
        "Arif Susam Kara Sevda",
        "Burak Kut Sözlerimi Geri Alamam",
        "Kayahan Yerine Sevemem",
        "Cemal Süreya Sevda Sözleri",
        "Server Uraz Gel Yanıma",
        "Korhan Futacı Peşimde",
        "İdo Tatlıses Bu Gece Son",
        "Murat Evgin Sevgiliye",
          // Türk Sanat Müziği - Sadece Aşk Acısı
        "Zeki Müren Elbet Bir Gün Buluşacağız",
        "Safiye Ayla Aldırma Gönül",
        "Müzeyyen Senar Hasret",
        "Bülent Ersoy İntizar",
        "Emel Sayın Gel Ey Seher",
        "Yıldız İbrahimova Sevdim",
        "Bekir Ünlüataer Unutama Beni",
        "Altan Uygur Sevdanızda",
          // Modern Aşk Acısı
        "Teoman Gemiler",
        "Şebnem Ferah Vazgeçtim Dünyadan",
        "Mor ve Ötesi Bir Derdim Var",
        "Duman Bu Akşam",
        "Gripin Böyle Kahpedir Dünya",
        "Çelik Nasıl Delirtin Beni",
        "Demir Demirkan Caney",
        "Vega Gözlerin",
        "Emre Aydın Afili Yalnızlık",
        "Göksel Sabır",
        "Pinhani Dur Bi Dakka",
        "Kargo Yalnızlık Ömür Boyu",
        
        // Çok Ağır Damar Şarkılar
        "Müslüm Gürses Mumya",
        "Müslüm Gürses Meyhaneci",
        "Müslüm Gürses Çile Bülbülü",
        "Müslüm Gürses Esrarlı Gözler",
        "Müslüm Gürses Hasret Rüzgarları",
        "Müslüm Gürses İçimde Yanar Bir Ateş",
        "Müslüm Gürses Kahroldum",
        "Müslüm Gürses Kısacık Bir Rüyaydı",
        "Müslüm Gürses Sana da Beyim",
        "Müslüm Gürses Sevda Yakar Beni",
        "Müslüm Gürses Son Defa",
        "Müslüm Gürses Susma Kalbim",
        "Müslüm Gürses Şu Yalan Dünya",
        "Müslüm Gürses Yalnız Yaşayıp",
        "Müslüm Gürses Buralarda Bir Kız Vardı",
        
        "İbrahim Tatlıses Ağlama Yarim",
        "İbrahim Tatlıses Aklımda Fikrimde Sen Varsın",
        "İbrahim Tatlıses Aramam",
        "İbrahim Tatlıses Çocukluk",
        "İbrahim Tatlıses Dert Nedir",
        "İbrahim Tatlıses Fosforlu Cevriyem",
        "İbrahim Tatlıses Gidiyorum",
        "İbrahim Tatlıses Hayırsız Evlat",
        "İbrahim Tatlıses İmdat",
        "İbrahim Tatlıses Masum",
        "İbrahim Tatlıses Mavi Süvari",
        "İbrahim Tatlıses Olmaz Olsun",
        "İbrahim Tatlıses Sabah Olmuyor",
        "İbrahim Tatlıses Sevmeyecek Gönlüm",
        "İbrahim Tatlıses Şaşkınım",
        "İbrahim Tatlıses Üç Kalp",
        "İbrahim Tatlıses Yaralıyım",
        "İbrahim Tatlıses Yüce Dağ Başında",
        "İbrahim Tatlıses Zoruna Gitti",
        "İbrahim Tatlıses Şu Kalbimin Efendisi",
        
        "Orhan Gencebay Gurbet Kuşu",
        "Orhan Gencebay İnsanoğlu",
        "Orhan Gencebay Garip Dostu",
        "Orhan Gencebay Küçük Yaşta",
        "Orhan Gencebay Pınar Başında",
        "Orhan Gencebay Sevdim",
        "Orhan Gencebay Ümit Hırsızı",
        "Orhan Gencebay Yaşama Sevinci",
        "Orhan Gencebay Zalim Sultan",
        "Orhan Gencebay Rüzgar",
        "Orhan Gencebay Tamirci Çırağı",
        "Orhan Gencebay Sevmek",
        "Orhan Gencebay Şarkım Dinle",
        "Orhan Gencebay Yol",
        "Orhan Gencebay Beyhude",
        "Orhan Gencebay Bir Sevda Masalı",
        "Orhan Gencebay Gönülden Gönüle",
        "Orhan Gencebay İstersen",
        "Orhan Gencebay Kalbim",
        "Orhan Gencebay Sevenler",
        
        "Ferdi Tayfur Ah Be Gülüm",
        "Ferdi Tayfur Aşkımız Bitecek",
        "Ferdi Tayfur Bak Beni Görsen Tanımazsın",
        "Ferdi Tayfur Çeşm-i Siyahım",
        "Ferdi Tayfur Gel Benim Ol",
        "Ferdi Tayfur Gülmemek Elde mi",
        "Ferdi Tayfur Haram Oldu",
        "Ferdi Tayfur Kalbimi Kırdığın Gün",
        "Ferdi Tayfur Kara Gözlüm",
        "Ferdi Tayfur Meyhaneci",
        "Ferdi Tayfur Neylersin",
        "Ferdi Tayfur Sorma",
        "Ferdi Tayfur Şoför",
        "Ferdi Tayfur Tek Başına",
        "Ferdi Tayfur Veda",
        "Ferdi Tayfur Yalnızlık",
        "Ferdi Tayfur Yar Dedin",
        "Ferdi Tayfur Yine Aynı Rüya",
        "Ferdi Tayfur Yokluğunda",
        "Ferdi Tayfur Zordur",
        
        // Kibariye ve Kadın Seslerin Ağır Parçaları
        "Kibariye Yaşamak Bu Değil",
        "Kibariye Yalan",
        "Kibariye Sen Affetsen Ben Affetmem",
        "Kibariye Ağlarım Hem de Çok Ağlarım",
        "Kibariye Bugün Aylardan Kasım",
        "Kibariye Kaçın Kurası",
        "Kibariye Kim Bilir",
        "Kibariye Kulakları Çın Çın Ötsün",
        "Kibariye Oy Benim Canım",
        "Kibariye Seni Seven Öldü",
        
        "Bülent Ersoy Çile Bülbülü",
        "Bülent Ersoy Dayanamıyorum",
        "Bülent Ersoy Dönülmeyen Yol",
        "Bülent Ersoy Ey Şuh-i Sertab",
        "Bülent Ersoy Geceler",
        "Bülent Ersoy Gecenin Kralı",
        "Bülent Ersoy Gesi Bağları",
        "Bülent Ersoy Hasret",
        "Bülent Ersoy İntizar",
        "Bülent Ersoy Kadınım",
        
        // Bergen Ağır Parçalar
        "Bergen Acılara Tutunmak",
        "Bergen Ah Yalan Dünya",
        "Bergen Bir Tek Aşkımsın",
        "Bergen Değmez Gözyaşım",
        "Bergen Hoş Geldin",
        "Bergen Kaçın Kurası",
        "Bergen Kim Bilir",
        "Bergen Sensizlik Ölüm Gibi",
        "Bergen Şarkı Söylemek Lazım",
        "Bergen Yaşanacak Günler Var",
        
        // Özcan Deniz Ağır
        "Özcan Deniz Aşkımız Yok",
        "Özcan Deniz Ateş",
        "Özcan Deniz Bir Demet Yasemen",
        "Özcan Deniz Bitmeyen Hikaye",
        "Özcan Deniz Bırak Beni",
        "Özcan Deniz Canın Sağ Olsun",
        "Özcan Deniz Esmerim",
        "Özcan Deniz Gitme",
        "Özcan Deniz Haram",
        "Özcan Deniz İnsaf",
        
        // Ağır Halk Müziği
        "Neşet Ertaş Ah Neyleyim",
        "Neşet Ertaş Boş Vermişem Dünyaya",
        "Neşet Ertaş Dağlarda Kar Olsam",        // Çok Ağır Modern Aşk Şarkıları
        "Teoman Ne Ekmek Ne de Su",
        "Teoman Papatya",
        "Teoman Rüya",
        "Teoman Sevdim Seni Bir Kere",
        "Teoman Serseri",
        "Teoman Son",
        "Şebnem Ferah Bu Aşk Fazla Sana",
        "Şebnem Ferah Can Kırıkları",
        "Şebnem Ferah Delgeç",
        "Şebnem Ferah Kim Haklıysa",
        "Şebnem Ferah Mayın Tarlası",
        "Şebnem Ferah Sigara",
        "Şebnem Ferah Yalnız",
        "Duman Ah",
        "Duman Dibine Kadar",
        "Duman Gönül",
        "Duman Helal Olsun",
        "Duman İçimdeki Duman",
        "Duman Kırık Hayallerim",
        "Duman Senden Daha Güzel",
        
        // Çok Ağır Slow
        "Tarkan Aşk Gitti Bizden",
        "Tarkan Gülümse Kaderine",
        "Tarkan Hup",
        "Tarkan İkimizin Yerine",
        "Tarkan Kır Zincirlerini",
        "Tarkan Ölürüm Sana",
        "Sertab Erener Aşk",
        "Sertab Erener Düş Bahçeleri",
        "Sertab Erener Kime Diyorum",
        "Sertab Erener Rengarenk",
        "Sertab Erener Sımsıkı",
        "Sertab Erener Yanarım",
        
        // Çok Ağır Türkçe Rock
        "Mor ve Ötesi Deli",
        "Mor ve Ötesi Gündüz Gece",
        "Mor ve Ötesi İki Yol",
        "Mor ve Ötesi Oyunbozan",
        "Mor ve Ötesi Sevda Sözleri",
        "Gripin Böyle Kahpedir Dünya",
        "Gripin Durma Yağmur Durma",
        "Gripin Elimde Değil",
        "Gripin Sensiz Ben",
        "Gripin Yanıyorum",
        
        "Model Beni Unutma",
        "Model Biraz Kafa Dengesi",
        "Model Gözümün Önü",
        "Model Of Of",
        "Model Yaşıyor",
        "110 Dayan",
        "110 Gözlerinde",
        "110 Hayat Bu",
        "110 Karpuz",
        "110 Öyle Bir Geçer Zaman Ki",
        
        // Çok Ağır Pop
        "Nilüfer Aşkın Nesi Var",
        "Nilüfer Canın Sağ Olsun",
        "Nilüfer Gidiyorum",
        "Nilüfer İçimde Aşkın Sesi",
        "Nilüfer Neden",
        "Nilüfer Nefes Nefese",
        "Nilüfer Sevemedim Karagözlüm",
        "Nilüfer Uykular",
        "Nilüfer Yara",
        "Yıldız Tilbe Ah Be Birader",
        "Yıldız Tilbe Bırakma Beni",
        "Yıldız Tilbe Delikanlım",
        "Yıldız Tilbe Eski Bir Rüya",
        "Yıldız Tilbe İçimdeki Duman",
        "Yıldız Tilbe Mecbur",
        "Yıldız Tilbe Yorgun"
    ],
    
    neseli: [
        // Pop Klasikleri
        "Barış Manço Dağlar Dağlar",
        "Tarkan Şımarık",
        "Sezen Aksu Şarkı Söylemek Lazım",
        "Ajda Pekkan Pet'r Oil",
        "Bülent Ersoy Geceler",
        "Erol Evgin Sevdim Seni Bir Kere",
        "Neşe Karaböcek Merhaba",
        "Nilüfer Erkeksi",
        "Sertab Erener Everyway That I Can",
        "Kenan Doğulu Çakkıdı",
        "Mustafa Sandal Jest Olur",
        "Gülşen Bangır Bangır",
        "Hadise Düm Tek Tek",
        "Simge Miş Miş",
        "Demet Akalın Afedersin",
        "Ebru Gündeş Rüya",
        "Işın Karaca Tatlı Dil",
        "Yıldız Tilbe Yorgun",
        "Sibel Can Padişah",
        "Bülent Serttaş Hoş Geldin",
        
        // Dans Müzikleri
        "Hande Yener Sen Yoluna Ben Yoluma",
        "Bengü Hoşçakal",
        "Emina Gine de Volim Te",
        "Murat Boz Janti",
        "Can Bonomo Meczup",
        "İrem Derici Zorunami",
        "Edis Dudak",
        "Mero Görüşürüz",
        "Aleyna Tilki Cevapsız Çınlama",
        "Reynmen Derdim Olsun",
        "Berkay Aşk Kırmızı",
        "Gökhan Özen Bombabomba",
        "İsmail YK Haydi Bastır",
        "Volkan Konak Mora",
        "Mahsun Kırmızıgül Beyaz Atlı",
        "Grup Vitamin Aman Doktor",
        "Burhan G Yanan Gemi",
        "Cenk Eren Hoşçakal",
        "Yaşar Gaga",
        "Erhan Güleryüz Sevdaluk",
        
        // Rock ve Alternatif Neşeli
        "Teoman Gemiler",
        "maNga Dursun Zaman",
        "Duman Bu Akşam",
        "Athena Yaşamaya Bak",
        "Model Biraz Kafa Dengesi",
        "Çelik Nasıl Delirtin Beni",
        "Demir Demirkan Caney",
        "Vega Gözlerin",
        "Göksel Sabır",
        "Manga We Could Be The Same",
        "Pinhani Dur Bi Dakka",
        "Yüzyüzeyken Konuşuruz Ateş Böceği",
        "Adamlar Rüya",
        "Kargo Yalnızlık Ömür Boyu",
        "Gripin Aşkı Memnu",
        "110 Öyle Bir Geçer Zaman Ki",
        "Model Sen De Gitme",
        "Duman Haberin Yok Ölüyorum",
        "Athena For Real",
        "maNga Bir Kadın Çizeceksin",
        
        // Rap ve Hip-Hop Neşeli
        "Şanışer Susamam",
        "Ceza Med Cezir",
        "Sagopa Kajmer Bir Pesimistin Gözyaşları",
        "Mode XL Rapstar",
        "Anıl Piyancı Ateş Parçası",
        "Canbay Wolker Herkes Mi Alacak",
        "Ben Fero Demet Akalın",
        "Gazapizm Heyecanı Yok",
        "Contra Pause",
        "Tankurt Manas Dur",
        "Norm Ender İsyandayım",
        "Şehinşah Yak",
        "Joker Flow",
        "Hayki Köprüaltı",
        "Ezhel Geceler",
        "Patron Patron",
        "Killa Hakan Gerçek",
        "Fuchs Yalan",
        "Server Uraz Rap",
        "Khontkar Geliyorum",
        
        // Anadolu Rock
        "Barış Manço Sarı Çizmeli Mehmet Ağa",
        "Cem Karaca Tamirci Çırağı",
        "Erkin Koray Cemalim",
        "Selda Bağcan İnce İnce",
        "Moğollar Katip Arzuhalim",
        "3 Hürel Geçti Dost Kervanı",
        "Mazhar Fuat Özkan Adımız Miskindir Bizim",
        "Bülent Ortaçgil Benimle Oynar Mısın",
        "Teoman İstanbul",
        "Şebnem Ferah Kim Haklı",
        "Mor ve Ötesi Cambaz",
        "Duman Senden Daha Güzel",
        "Gripin Sensiz İstanbul",
        "Model Ucuz Roman",
        "110 Seytan Bunun Neresinde",
        "Athena Holigan",
        "maNga Bitti Rüya",
        "Kargo Zor Yıllar",
        "Vega Elimde Değil",
        "Göksel İçimdeki Fırtına",
        
        // Eğlenceli Türküler
        "Neşet Ertaş Yalan Dünya",
        "Aşık Mahzuni Şerif Dom Dom",
        "Hasret Gültekin Bahar Geldi",
        "Arif Sağ Yürüye Yürüye",
        "Musa Eroğlu Dağlar",
        "Özkan Meydan Horon",
        "Ali Ekber Çiçek Çiftetelli",
        "Volkan Konak Lokum",
        "Fahir Atakoğlu Anadolu",
        "Kardeş Türküler Çocuklar",
        "Sıla Afitap",
        "Kubat Yaralı",
        "Kalben Sadece",
        "Gece Yolcuları Kıyıda",
        "Yaprak Çamlıca Bak",
        "Nev Aşk Olsun",
        "Zeynep Casalini Dans Et",
        "Özlem Tekin Aşk Herşeyi Affeder Mi",
        "Aylin Aslım Keşke",
        "Kaan Tangöze Bir Fırtına Tut Ki Beni"
    ],
    
    abukSubuk: [
        // Garip Pop Şarkıları
        "Cüneyt Özdemir Dolap Beygiri",
        "Gökhan Özen Bombabomba",
        "İsmail YK Haydi Bastır",
        "Volkan Konak Mora",
        "Mahsun Kırmızıgül Beyaz Atlı",
        "Grup Vitamin Aman Doktor",
        "Burhan G Yanan Gemi",
        "Cenk Eren Hoşçakal",
        "Yaşar Gaga",
        "Erhan Güleryüz Sevdaluk",
        "Mustafa Yıldızdoğan Resimdeki Gözyaşları",
        "Ziynet Sali Aşk",
        "Kibariye Yaşamak Bu Değil",
        "Baha Elveda",
        "Özcan Deniz Ask",
        "Alişan Sevdim Seni",
        "Ata Demirer Kolbastı",
        "Gülşah Küçük Küçük Hayaller",
        "Tuğba Özerk Aşkın Mapushane",
        "Ebru Polat Kim Demiş",
        
        // Çılgın Arabesk
        "Hülya Avşar Yakarım Canını",
        "Cengiz Kurtoğlu Seni Seviyorum",
        "Özgür Çevik Karagözlüm",
        "Sibel Tüzün Yanıyorum",
        "Murat Göğebakan Neden",
        "Yonca Evcimik Gözlerinin Hapsindeyim",
        "Levent Yüksel Darılma",
        "Kadir Çöpdemir Yorgunum",
        "Armağan Sanki Rüya",
        "Grup Hepsi Olmaz Oğlan",
        "Nil Karaibrahimgil Parmak Uçlarında",
        "Keremcem Canım",
        "Yavuz Bingöl Ela Gözlerin",
        "Ferhat Göçer Sevdaluk",
        "Özgün Müzik Bu Gece",
        "İskender Paydaş Yorgunum",
        "Murat Uyar Sevda Yelleri",
        "Burcu Güneş Yanıyorum",
        "Baran Aşkım",
        "Server Uraz Gel Yanıma",
        
        // Absürt Şarkılar
        "Korhan Futacı Peşimde",
        "İdo Tatlıses Bu Gece Son",
        "Murat Evgin Sevgiliye",
        "Arif Susam Kara Sevda",
        "Burak Kut Sözlerimi Geri Alamam",
        "Kayahan Yerine Sevemem",
        "Cemal Süreya Sevda Sözleri",
        "Ümit Besen Nikah Masası",
        "Özdemir Erdoğan Gurbet",
        "Berdan Mardini Kırgınım",
        "Yaşlı Amca Deli Divane",
        "Dj Akman Patlamaya Devam",
        "Serdar Ortaç Sigara",
        "Hakan Altun Gitme",
        "Ümit Sayın Yoruldum",
        "Ceylan Avşaroğlu Sevgilim",
        "Müzeyyen Senar Dans",
        "Zara Kaçak",
        "Bengü Hoş Geldin",
        "Emina Sandım Ki",
        
        // Komik Türküler
        "Volkan Konak Lokum",
        "Ali Ekber Çiçek Horon",
        "Ömer Faruk Bostan Çiftetelli",
        "Halil İbrahim Sofrası Halay",
        "Yusuf Harputlu Zeybek",
        "Cihan Mürtezaoğlu Ağırlama",
        "Mustafa Özarslan Karşılama",
        "Ergün Bayrak Bar",
        "Mehmet Akbulut Oyun Havası",
        "İsmet Özel Roman",
        "Selahattin Alpay Çiftetelli",
        "Recep Özdilek Horon",
        "Turan Şahin Zeybek",
        "Ekrem Çelebi Halay",
        "Fahrettin Güneş Oyun",
        "Murat Çobanoğlu Bar",
        "Sinan Akçıl Adeyyo",
        "Hasan Yıldırım Süper",
        "Özgür Atlas Dans",
        "Kenan İmirzalıoğlu Şarkı",
        
        // Enteresan Remixler
        "Gökhan Özen Remix",
        "İsmail YK Remix",
        "Volkan Konak Remix",
        "Mahsun Kırmızıgül Remix",
        "Ceza Remix",
        "Tarkan Remix",
        "Sezen Aksu Remix",
        "Barış Manço Remix",
        "Müslüm Gürses Remix",
        "İbrahim Tatlıses Remix",
        "Ajda Pekkan Remix",
        "Bülent Ersoy Remix",
        "Neşe Karaböcek Remix",
        "Nilüfer Remix",
        "Sertab Erener Remix",
        "Kenan Doğulu Remix",
        "Mustafa Sandal Remix",
        "Gülşen Remix",
        "Hadise Remix",
        "Demet Akalın Remix"
    ]
};
